### ISSUE TITLE
Input Data Types

### ISSUE THREAD

**Issue by JaylenJames** [RichardCouperthwaite/plt-editor-tool#9]
Hey Richard, it's Jaylen. First, thanks for this code! The issue I'm having is with the input type of the x data. This may be an easy issue to solve that I am doing wrong, but I'm getting the error _object of type 'int' has no len()_. I tried changing my x-axis data values to a numpy array of int64 values, but got the issue of _object of type 'numpy.int64' has no len()_. If anything, this possibly could make your code more robust by allowing more data types to be input.

**Comment by RichardCouperthwaite** [comment]
Thank you for the issue, Jaylen. Please make sure that you are sending the data as part of a list. The current code only accepts the input data as a list of arrays, even if there is only one data-set that is being plotted. I will attempt to add a check that will allow the plotEditor module to accept the equivalent to a single Numpy array without raising an error.

**Comment by JaylenJames** [comment]
I see. Very interesting. I’ll have to make that edit when I return to working on that project this week. Thank you!

**Comment by RichardCouperthwaite** [comment]
Version 2.0.7 includes several advanced options for loading data into the plot editor tool.
1) The traditional Set of Lists Method
2) 1D Numpy Arrays for single data-set
3) 2D Numpy Arrays for multiple data-sets
4) 3D Numpy Array for multiple data-sets
5) Pandas Dataframe

Please see the Usage Guide pdf in the main directory for more information and code snippets for how to use each of the input methods.

**Comment by JaylenJames** [comment]
Awesome! Thank you!
